name: Build and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Lint
      working-directory: ./frontend
      run: npm run lint
    
    - name: Build with increased memory
      working-directory: ./frontend
      run: NODE_OPTIONS="--max-old-space-size=8192" npm run build:prod
    
    - name: Run tests
      working-directory: ./frontend
      run: npm test
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: frontend/build/
    
    - name: Create build size report
      working-directory: ./frontend
      run: |
        echo "# Build Size Analysis" > build-report.md
        echo "## File sizes after gzip:" >> build-report.md
        ls -lh build/static/js/*.js | awk '{print "- " $9 ": " $5}' >> build-report.md
        ls -lh build/static/css/*.css | awk '{print "- " $9 ": " $5}' >> build-report.md
    
    - name: Upload build report
      uses: actions/upload-artifact@v3
      with:
        name: build-report
        path: frontend/build-report.md

  analyze:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Generate bundle analysis
      working-directory: ./frontend
      run: |
        NODE_OPTIONS="--max-old-space-size=8192" ANALYZE=true GENERATE_SOURCEMAP=true npm run build:prod
    
    - name: Upload bundle stats
      uses: actions/upload-artifact@v3
      with:
        name: bundle-stats
        path: frontend/bundle-stats.json